name: CI/CD Pipeline

on:
   push:
      branches:
        - main

jobs:
  build:
    run-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint and Test
      run: |
        flake8 .
        pytest   

    - name: Build Docker Image
      run: |
        docker build -t healthcare-fraud-detection-app .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Streamlit Sharing
      run: echo "Deployment to Streamlit Sharing is manual for now."